sudo: required

# Use Travis' Ubuntu Trusty machines. They have more RAM.
# It does not affect which OSs we are testing, since they all provided
# by Docker containers. This simply defines which OS Docker itself will
# be running on.
dist: trusty

services:
  - docker

language: ruby

rvm:
  - 1.9.3

script:
  # Some of our test can take long time, and not output anything while they
  # are running. If this goes on for too long (ten minutes), then Travis
  # will assume the build has stalled, and kill it.
  #
  # It' a bit cheeky, but lets make sure that _something_ goes to STDOUT
  # every five minutes, so that our build won't be killed unjustly.
  - (while true; do date --iso-8601=seconds; sleep 300; done) &
  - (if [[ -n $TRAVIS_TEST_UNIT ]]; then make test-unit; else bundle exec rake beaker; fi)

env:
  global:
    - TRAVIS_CI=true
    - LOGSTASH_VERSION=2.3.2
    - BEAKER_PE_DIR=spec/fixtures/artifacts
  matrix:
    # Run the unit tests once.
    - TRAVIS_TEST_UNIT=true

    # Then run the acceptance tests across the matrix.
    - PUPPET_VERSION=3.2.4 BEAKER_set=centos-6
    - PUPPET_VERSION=3.3.2 BEAKER_set=centos-6
    - PUPPET_VERSION=3.4.3 BEAKER_set=centos-6
    - PUPPET_VERSION=3.5.1 BEAKER_set=centos-6
    - PUPPET_VERSION=3.6.2 BEAKER_set=centos-6
    - PUPPET_VERSION=3.7.5 BEAKER_set=centos-6
    - PUPPET_VERSION=3.8.6 BEAKER_set=centos-6
    - PUPPET_VERSION=4.4.2 BEAKER_set=centos-6
    - PUPPET_VERSION=3.8.4 BEAKER_set=centos-6 BEAKER_PE_VER=3.8.4 BEAKER_IS_PE=true

    - PUPPET_VERSION=3.2.4 BEAKER_set=centos-7
    - PUPPET_VERSION=3.3.2 BEAKER_set=centos-7
    - PUPPET_VERSION=3.4.3 BEAKER_set=centos-7
    - PUPPET_VERSION=3.5.1 BEAKER_set=centos-7
    - PUPPET_VERSION=3.6.2 BEAKER_set=centos-7
    - PUPPET_VERSION=3.7.5 BEAKER_set=centos-7
    - PUPPET_VERSION=3.8.6 BEAKER_set=centos-7
    - PUPPET_VERSION=4.0.0 BEAKER_set=centos-7
    - PUPPET_VERSION=4.1.0 BEAKER_set=centos-7
    - PUPPET_VERSION=4.2.3 BEAKER_set=centos-7
    - PUPPET_VERSION=4.3.2 BEAKER_set=centos-7
    - PUPPET_VERSION=4.4.2 BEAKER_set=centos-7

    - PUPPET_VERSION=3.2.4 BEAKER_set=debian-7
    - PUPPET_VERSION=3.3.2 BEAKER_set=debian-7
    - PUPPET_VERSION=3.4.3 BEAKER_set=debian-7
    - PUPPET_VERSION=3.5.1 BEAKER_set=debian-7
    - PUPPET_VERSION=3.6.2 BEAKER_set=debian-7
    - PUPPET_VERSION=3.7.5 BEAKER_set=debian-7
    - PUPPET_VERSION=3.8.6 BEAKER_set=debian-7
    - PUPPET_VERSION=4.4.2 BEAKER_set=debian-7
    - PUPPET_VERSION=3.8.4 BEAKER_set=debian-7 BEAKER_PE_VER=3.8.4 BEAKER_IS_PE=true

    # 3.2 and 3.3 won't work on debian-8.
    # REF: https://github.com/puppetlabs/puppet/pull/2184
    # - PUPPET_VERSION=3.2.4 BEAKER_set=debian-8
    # - PUPPET_VERSION=3.3.2 BEAKER_set=debian-8
    - PUPPET_VERSION=3.4.3 BEAKER_set=debian-8
    - PUPPET_VERSION=3.5.1 BEAKER_set=debian-8
    - PUPPET_VERSION=3.6.2 BEAKER_set=debian-8
    - PUPPET_VERSION=3.7.5 BEAKER_set=debian-8
    - PUPPET_VERSION=3.8.6 BEAKER_set=debian-8
    - PUPPET_VERSION=4.4.2 BEAKER_set=debian-8

    # 3.2 and 3.3 won't work on opensuse-13
    # REF: https://github.com/puppetlabs/puppet/pull/2184
    # - PUPPET_VERSION=3.2.4 BEAKER_set=opensuse-13
    # - PUPPET_VERSION=3.3.2 BEAKER_set=opensuse-13
    - PUPPET_VERSION=3.4.3 BEAKER_set=opensuse-13
    - PUPPET_VERSION=3.5.1 BEAKER_set=opensuse-13
    - PUPPET_VERSION=3.6.2 BEAKER_set=opensuse-13
    - PUPPET_VERSION=3.7.5 BEAKER_set=opensuse-13
    - PUPPET_VERSION=3.8.6 BEAKER_set=opensuse-13

    - PUPPET_VERSION=3.2.4 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=3.3.2 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=3.4.3 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=3.5.1 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=3.6.2 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=3.7.5 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=3.8.6 BEAKER_set=ubuntu-1204
    - PUPPET_VERSION=4.4.2 BEAKER_set=ubuntu-1204

    - PUPPET_VERSION=3.2.4 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=3.3.2 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=3.4.3 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=3.5.1 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=3.6.2 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=3.7.5 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=3.8.6 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=4.4.2 BEAKER_set=ubuntu-1404
